<a href="https://colab.research.google.com/github/SevdeSalkim/Dice_game/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
import numpy as np

In [3]:
print ( tf . __version__ )


2.15.0


Bir skaler, sıra 0 tensör olarak bilinir. Çünkü boyutları yoktur (sadece bir sayıdır).

In [5]:
skaler = tf.constant(7)
skaler.ndim

0

vektörler 1 boyutludur.

In [6]:
vektör = tf.constant([1,2])
vektör.ndim

1

In [8]:
matris = tf.constant([[1,2],[2,3]])
matris.ndim

2

tip dönüşümü tensorflow genelde int32 olarak tanımlar.

In [9]:
new_matris = tf.constant([[1,2,3],[4,5,6]] , dtype = tf . float16 )
new_matris

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [ ]:
tensör  =  tf . sabit ([[[ 1 ,  2 ,  3 ],
                       [ 4 ,  5 ,  6 ]],
                      [[ 7 ,  8 ,  9 ],
                       [ 10 ,  11 ,  12 ]],
                      [[ 13 ,  14 ,  15 ],
                       [ 16 ,  17 ,  18 ]]])
tensör

* Skaler : Tek bir sayı.
* vektör : yönü olan bir sayı (örn. yönü olan rüzgar hızı).
* matris : 2 boyutlu bir sayı dizisi.
* tensör : n boyutlu bir sayı dizisi (burada n herhangi bir sayı olabilir, 0 boyutlu bir tensör bir skalerdir, 1 boyutlu bir tensör bir vektördür).

tf.Variable() ile tensör oluşturma.
tf.constant() aksine Variable ile oluşturulan değiştirilebilir.

In [11]:
değiştirilebilir_tensör = tf.Variable([7,3])
değiştirilemez_tensör = tf.constant([1,3])
değiştirilebilir_tensör , değiştirilemez_tensör

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [13]:
değiştirilebilir_tensör [0] = 5
değiştirilebilir_tensör

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
değiştirilebilir_tensör[0].assign(4)
değiştirilebilir_tensör

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 3], dtype=int32)>

# Burada hata almamızın sebebi constant ile oluşturulan tensörler değiştirilemezlerdir.

In [15]:
değiştirilemez_tensör[0].assign(9)
değiştirilemez_tensör

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Rastgele tensörler oluşturma

In [18]:
random_1 = tf.random.Generator.from_seed(13)
random_1 =random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 =random_2.normal(shape=(3,2))
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

# Shuffle a tensor

In [22]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [23]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

Birlerden oluşan tensör

In [7]:
tf.ones(shape=(3,2))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

Sıfırlardan oluşan tensör

In [8]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [11]:

np_array = np.arange(1, 25, dtype=np.int32)
A = tf.constant(np_array,
                shape=[2, 4, 3])
np_array, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [13]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])  # 2 grup her grupta 3 matris , 4x5 matris oluşturur.
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


# Tensörleri python list gibi şekillendirebiliriz.

In [17]:
# Her boyutun ilk 2 öğesini alın
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
# Sonuncusu hariç her dizinden boyutu alın
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
# Rank 2 tensör oluşturun (2 boyut)
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
# Her satırın son öğesini alın
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

# tf.newaxis, bir boyut eklemek veya mevcut boyutları yeniden boyutlandırmak için kullanılır ve tensörlerin şeklini değiştirmeye yardımcı olur.

In [21]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

aynı işlemi tf.expand ile yapabiliriz.

In [22]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" son eksen anlamına gelir

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Temel işlemler

In [24]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [25]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

çarpma işleminin tensorflow komutu

In [26]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matris Çarpımı
# tf.matmul()
Matris çarpımında hatırlanması gereken iki ana kural şunlardır:
* iç boyutlar eşleşmelidir ÖR: (5,3) @ (3, 4)
* Ortaya çıkan matris dış boyutların şekline sahiptir: (5,3) @ (3, 4) = (5 , 4)

" @ " Pythonda Matris Çarpım sembolüdür.

In [27]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [28]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [29]:
# (3, 2) tensörünü oluşturun
X  =  tf.constant ([[ 1 ,  2 ],
                 [ 3 ,  4 ],
                 [ 5 ,  6 ]])

# Başka bir (3, 2) tensörü oluşturun
Y  =  tf.constant([[ 7 ,  8 ],
                 [ 9 ,  10 ],
                 [ 11 ,  12 ]])
X ,  Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [31]:
X @ Y # Hata almamımız sebebi matris çarpım kuralına uyulmamasından kaynaklı (3,2) * (3,2) matris çarpımı için uygun değildir.

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [34]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [36]:
X @ tf.transpose(Y) # Y matrisinin transpozunu alarak (2,3) matrise dönüştürdük. Bu sebeple çarpım işlemimimiz kurallara uygun hale geldi

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [44]:
# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [41]:
tf.reshape(Y, shape=(2, 3)) # Transpoz yerine reshape komutunu kullanarak matrisimizi yeniden boyutlandırabiliriz.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [43]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

# Nokta Çarpımı

In [45]:
# X ve Y üzerinde nokta çarpımını gerçekleştirin (X'in transpoze edilmesini gerektirir)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [46]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Bir tensörün veri tipini değiştirme
* Bir tensörün veri tipini tf.cast() kullanarak değiştirebilirsiniz

In [47]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [48]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

Mutlak değerin elde edilmesi

In [50]:
D = tf.constant([-7, 10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Minimum, maksimum, ortalama, toplamı bulma
* tf.reduce_min()- tensördeki minimum değeri bulun.
* tf.reduce_max()- tensördeki maksimum değeri bulun (en yüksek tahmin olasılığını bulmak istediğinizde faydalıdır).
* tf.reduce_mean()- tensördeki tüm elemanların ortalamasını bulun.
* tf.reduce_sum()- bir tensördeki tüm elemanların toplamını bulun.

In [51]:
# 0 ile 100 arasında 50 rastgele değere sahip bir tensör oluşturun
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([77, 31, 59, 75, 82, 40,  9, 15, 89, 21, 88,  0, 54, 89, 92, 26, 26,
       99, 78, 29, 23, 87, 90, 64, 72, 33, 64, 13, 37, 73, 46, 95, 56,  0,
       34, 27, 37, 35, 12, 85, 11, 50, 73,  8, 17, 88, 73,  4, 74, 66])>

In [52]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [53]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [54]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [55]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2526>

## Konumsal maksimum ve minimumu bulma
* tf.argmax()- belirli bir tensördeki maksimum elemanın konumunu bulun.
* tf.argmin()- belirli bir tensördeki minimum elemanın konumunu bulun.

In [59]:
# 0 ile 1 arasında 50 değere sahip bir tensör oluşturun
F = tensor = tf.linspace(start=0.0, stop=1.0, num=50)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204081, 0.12244898, 0.14285713, 0.1632653 , 0.18367347,
       0.20408162, 0.2244898 , 0.24489796, 0.26530612, 0.28571427,
       0.30612245, 0.3265306 , 0.34693876, 0.36734694, 0.3877551 ,
       0.40816325, 0.42857143, 0.4489796 , 0.46938774, 0.48979592,
       0.5102041 , 0.53061223, 0.5510204 , 0.57142854, 0.59183675,
       0.6122449 , 0.63265306, 0.6530612 , 0.67346936, 0.6938775 ,
       0.7142857 , 0.7346939 , 0.75510204, 0.7755102 , 0.79591835,
       0.8163265 , 0.83673465, 0.85714287, 0.877551  , 0.8979592 ,
       0.9183673 , 0.9387755 , 0.95918363, 0.97959185, 1.        ],
      dtype=float32)>

In [60]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [61]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [62]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 49
The maximum value of F is: 1.0
Using tf.argmax() to index F, the maximum value of F is: 1.0
Are the two max values the same (they should be)? True



# Tensörü sıkıştırmak (tüm tek boyutları kaldırmak)
* tf.squeeze()- tensörden 1'in tüm boyutlarını kaldırın.

In [6]:
# 0 ile 100 arasında 50 sayıdan oluşan 5. (5 boyutlu) tensör oluşturun
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [7]:
# Tensör G'yi sıkıştırın (1 boyutun tamamını kaldırın)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# One-hot encoding

In [10]:
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [11]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

#Kare alma, log, karekök
* tf.square()- tensördeki her değerin karesini alın.
* tf.sqrt()- tensördeki her değerin karekökünü alın ( not: elemanların kayan nokta olması gerekir, aksi takdirde hata olur).
* tf.math.log()- tensördeki her değerin doğal logunu alın (elemanların yüzmesi gerekir).

In [12]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [13]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [16]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [17]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [18]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [19]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# tf.VariableTensörleri manipüle etmek
İle oluşturulan tensörler tf.Variable()aşağıdaki gibi yöntemler kullanılarak yerinde değiştirilebilir:

* .assign()- değişken tensörün belirli bir indeksine farklı bir değer atayın.
* .add_assign()- mevcut bir değere ekleme yapın ve onu değişken tensörün belirli bir indeksine yeniden atayın.

In [20]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [21]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [22]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# Tensors and NumPy
* np.array()- bir ndarray'e (NumPy'nin ana veri türü) dönüştürmek için bir tensör iletin.
* tensor.numpy()- ndarray'e dönüştürmek için bir tensör çağırın.

In [23]:
# NumPy dizisinden bir tensör oluşturun
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [24]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [25]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [26]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# @tf.function, bir Python fonksiyonunu çağrılabilir bir TensorFlow grafiğine dönüştürür.

In [27]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [28]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>